### ISSUE TITLE
Can I specify the Microsoft.CodeAnalysis.CSharp package version myself

### ISSUE THREAD

**Issue by ljnober** [ByronMayne/SourceGenerator.Foundations#16]
I use other packages depend on Microsoft. CodeAnalysis. CSharp 4.8.0 version.but the  SourceGenerator.Foundations add the 4.3.1 to the .csproj file.

**Comment by ByronMayne** [comment]
I can remove the reference that is explicitly added. I only originally did it because I wanted it to be super simple to setup.
